### ISSUE TITLE
auth_session_timeout- Traceback (most recent call last) Error

### ISSUE THREAD

**Issue by prajithpipt** [OCA/server-auth#134]
I installed odoo 12 in centOS7 server
When i check the odoo log, sometimes below mentioned error appears and the service stopped.

Traceback (most recent call last):
  File "/home/Odoo12/odoo12/custom_addons/auth_session_timeout/models/res_users.py", line 74, in _auth_timeout_check
    expired = getmtime(path) < deadline
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/home/Odoo12/.local/share/Odoo/sessions/werkzeug_438ccef416264f0acdcb5bfb772f$

Please help me to fix this.....

**Comment by Tariqlab** [comment]
Comment res_users.py from line 69 up to 78
and restart odoo server. this will fix your issue
