### ISSUE TITLE
[12.0] pip lasso requirements.txt fail

### ISSUE THREAD

**Issue by igallart** [OCA/server-auth#192]
lasso fail with pip (ubuntu18.04, ubuntu 20.04):

pip3 install lasso
Collecting lasso
  Downloading https://files.pythonhosted.org/packages/4e/8d/515757f262f53ed72e7695a2274097aafe0aa28d8017fb6e7c357baab2ab/lasso-0.0.5.tar.gz
Collecting delorean>=0.4.4 (from lasso)
  Downloading https://files.pythonhosted.org/packages/76/40/5e8d179a0311236b2e83aa1c80b0b363700035ad6639858c75ef5be975e6/Delorean-1.0.0.tar.gz
Collecting schema<0.4.0,>=0.3.1 (from lasso)
  Downloading https://files.pythonhosted.org/packages/0c/1f/1bb243c03e7109f18256b0485c6a1c400019a76d023f36983c99232c0141/schema-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bl27l9pf/schema/setup.py", line 16, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2360: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bl27l9pf/schema/

In github, the project is now https://github.com/aperezdc/gnarl, maybe we should exchange lasso for gnarl?

**Comment by igallart** [comment]
I try today and it is installed, I close issue.
