### ISSUE TITLE
[12.0] auth_totp enabled but nothing happens

### ISSUE THREAD

**Issue by miscs** [OCA/server-auth#235]
Hi all,

I just installed and enabled auth_totp for my user and tested it with a private browser instance (chrome and safari) but nothing happens - I can just login with username/password like before. No second authentication screen to enter a code is shown.

I also checked logs, but found nothing suspicious.

Any hints would be highly appreciated. Thanks!
Steve

![image](https://user-images.githubusercontent.com/878463/100540126-99386000-323b-11eb-8bb2-61cdf33b64a9.png)

**Comment by i-vyshnevska** [comment]
you need to finish installation through the wizard "Add New App/Device"

**Comment by miscs** [comment]
Hi @i-vyshnevska 

thank for your reply, but I completed the wizard. You can see this in the screenshot of my first post. I attached Authy as app successfully.

Thanks
Steve

**Comment by i-vyshnevska** [comment]
try to integrate this code https://github.com/OCA/server-auth/pull/188/files

**Comment by i-vyshnevska** [comment]
and this one https://github.com/OCA/server-auth/pull/158

**Comment by miscs** [comment]
Thank you for your answer. I will pull these changes and try again after christmas break. I will report back.

**Comment by miscs** [comment]
Hi @i-vyshnevska,

I pulled #188 and updated the module, restarted the server and registered an app using the wizard. Now I get a 500 server error when I try to login.
I can select my database and enter my username und PW, but after submit the 500er pops up. 

`
2020-12-31 11:26:12,844 32331 INFO mydb werkzeug: 127.0.0.1 - - [31/Dec/2020 11:26:12] "GET /web?db=mydb HTTP/1.0" 303 - 1 0.001 0.004
2020-12-31 11:26:13,684 32331 INFO mydb werkzeug: 127.0.0.1 - - [31/Dec/2020 11:26:13] "GET /web/login HTTP/1.0" 200 - 369 0.230 0.570
2020-12-31 11:26:13,840 32331 INFO mydb werkzeug: 127.0.0.1 - - [31/Dec/2020 11:26:13] "POST /website/translations HTTP/1.0" 200 - 11 0.011 0.011
2020-12-31 11:26:18,097 32332 INFO mydb odoo.addons.base.models.res_users: Login successful for db:None login:myuser from 127.0.0.1 
2020-12-31 11:26:18,105 32332 ERROR mydb odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/website/controllers/main.py", line 97, in web_login
    if not redirect and request.params['login_success']:
KeyError: 'login_success'
 
2020-12-31 11:26:18,149 32332 INFO mydb werkzeug: 127.0.0.1 - - [31/Dec/2020 11:26:18] "POST /web/login HTTP/1.0" 500 - 48 0.033 0.280
`

Strange for me is 
`
2020-12-31 11:26:18,097 32332 INFO mydb odoo.addons.base.models.res_users: Login successful for db:None login:myuser from 127.0.0.1 
`
Why it says DB:None? I selected the db before login and this worked all the time before I pulled #188.

Thanks
Steve

**Comment by miscs** [comment]
I just switched back to branch 12.0 and the error is gone, so I can login without problems. But without MFA...

**Comment by i-vyshnevska** [comment]
well we are using the mentioned PR on a few projects they are  working fine
reading your steps maybe you need to update "auth_totp" after the server restart

**Comment by miscs** [comment]
Thanks for your feedback. I updated everything, restarted the server and updated "auth_totp" after server restart. Still getting the above 500 error.

Could you maybe check in the logs if you also get this db:None log message at one of your installs? This still looks stange for me. Thanks!

**Comment by miscs** [comment]
another question concerning this problem: we also use ldap. maybe this could be a problem?
