### ISSUE TITLE
[15.0] Module "auth saml" failing to authenticate users despite the success of the authentication phase

### ISSUE THREAD

**Issue by benjauger** [OCA/server-auth#357]
First of all, thank you all for your time :) . The impacted module is "auth saml" that failing to authenticate the users despite the success of the authentication phase through the IDP.

## Module
**auth_saml**

## Describe the bug
The auth_saml provide a working authentication phase (according to the logs) but result in a failed login of user. The displayed message is "_You do not have access to this database. Please contact support._" which is not true because the same user can login with the login form through LDAP. I added a copy of logs in addition. 

Our IDP is an ADFS, correctly configured and already working with many other tools (gitlab, nextcloud etc), so that's not our first try. 

We run the auth_saml module on Odoo 15. As the documentation explains, we created an user and tied him with with the SAML provider (upn = email address) then we tried to login, unsucessfuly.

Here is the log : 
```text 
2022-03-21 21:22:13,585 1997762 INFO odoo saml2.client: destination to provider: https://sso.foo.com/adfs/ls/
2022-03-21 21:22:13,586 1997762 INFO odoo saml2.entity: REQUEST: <ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-caFcSxxDOvH7sSZza" Version="2.0" IssueInstant="2022-03-21T21:22:13Z" Destination="https://sso.foo.com/adfs/ls/" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://odoo.foo.com/auth_saml/signin"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://odoo.foo.com/odoo-saml/customsamlforfoo</ns1:Issuer></ns0:AuthnRequest>
2022-03-21 21:22:13,586 1997762 INFO odoo saml2.client: AuthNReq: <ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-caFcSxxDOvH7sSZza" Version="2.0" IssueInstant="2022-03-21T21:22:13Z" Destination="https://sso.foo.com/adfs/ls/" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://odoo.foo.com/auth_saml/signin"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://odoo.foo.com/odoo-saml/customsamlforfoo</ns1:Issuer></ns0:AuthnRequest>
2022-03-21 21:22:13,586 1997762 INFO odoo saml2.entity: HTTP REDIRECT
2022-03-21 21:22:13,591 1997762 INFO odoo werkzeug: 172.16.3.202 - - [21/Mar/2022 21:22:13] "GET /auth_saml/get_auth_request?pid=1 HTTP/1.0" 303 - 8 0.002 0.025
2022-03-21 21:22:13,728 1997761 INFO odoo saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
2022-03-21 21:22:13,746 1997761 INFO odoo saml2.response: Subject NameID: <ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">benjamin@foo.com</ns0:NameID>
2022-03-21 21:22:13,747 1997761 INFO odoo saml2.client_base: --- ADDED person info ----
2022-03-21 21:22:13,808 1997761 INFO odoo odoo.addons.base.models.res_users: Login failed for db:odoo login:benjamin@foo.com from 172.16.3.202
2022-03-21 21:22:13,808 1997761 INFO odoo odoo.addons.auth_saml.controllers.main: SAML2: access denied
2022-03-21 21:22:13,821 1997761 INFO odoo werkzeug: 172.16.3.202 - - [21/Mar/2022 21:22:13] "POST /auth_saml/signin HTTP/1.0" 303 - 78 0.035 0.105
2022-03-21 21:22:13,863 1997770 INFO odoo werkzeug: 172.16.3.202 - - [21/Mar/2022 21:22:13] "GET /web/login?saml_error=expired HTTP/1.0" 200 - 17 0.006 0.014
```

We can notice the **saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>**

And the **Login failed for db:odoo login:benjamin@foo.com from 172.16.3.202**

## To Reproduce
**Affected versions**: 15

No real way to reproduce except set up an ADFS ... ? :(

**Expected behavior**
User should be connected and redirected on the homepage after the authentication phase is ended successfully.

**Additional context**
Python is 3.9, Odoo is entreprise licenced version (15), the IDP is ADFS (sso.foo.com).

**Comment by benjauger** [comment]
I took a deeper look into the code of the plugin to debug and I didnt get the point here:

https://github.com/OCA/server-auth/blob/cbe9c0568c53358181411b63a83777d7cb1b5089/auth_saml/controllers/main.py#L194

I get a successful authentication phase with IDP and get a valid (as I understand) credentials object:

```code
Arguments: (('odoo', 'benjamin@foo.com', 'PHNhbWxwOlJlc3BvbnNlIElEPSJfNTY1ZTIyZWEtNzBl...'))
```
Maybe i'm totaly wrong and I missed something but it's like the authentication is forwarded to Odoo internal mechanism (with the nameid persistent email) that would fail... Any idea @vincent-hatakeyama ?

**Comment by vincent-hatakeyama** [comment]
Are you using the code in #342? That look like one of the error I fixed; the token was not written to the database so can not be accessed in the other transaction.

**Comment by benjauger** [comment]
Hello @vincent-hatakeyama , I've just tried your version https://github.com/xcgd/server-auth/tree/topic/15.0/auth_saml but unfortunatly, the following exception is throw at the installation phase:

```code
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 644, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 302, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /var/lib/odoo/.local/share/Odoo/specific/addons/server-auth/auth_saml/views/auth_saml.xml:44
Error while validating view near:

                <field name="active" widget="boolean_toggle"/>
                <field name="autoredirect"/>
            </tree>
Field "autoredirect" does not exist in model "auth.saml.provider"

View error context:
{'file': '/var/lib/odoo/.local/share/Odoo/specific/addons/server-auth/auth_saml/views/auth_saml.xml',
 'line': 6,
 'name': 'auth.saml.provider.list',
 'view': ir.ui.view(2582,),
 'view.model': 'auth.saml.provider',
 'view.parent': ir.ui.view(),
 'xmlid': 'view_saml_provider_list'}
```

Seem's that the new field **autoredirect** is missing somewhre in the model **auth.saml.provider**...
I can give another try once the module would installing well 👍

**Comment by vincent-hatakeyama** [comment]
It’s not missing, you forgot to update the module because some models are changed.

CI installs the module and there’s tests of it, it would have been visible if there was such a problem. That’s on top of tests I did myself with a local keycloak.

**Comment by gurneyalex** [comment]
for the record I have similar issue using Azure AD and this module. I'm currently investigating.

**Comment by gurneyalex** [comment]
OK some debugging hinted towards a wrong setting on "**Identity Provider matching attribute**". I was using the wrong value (the default `subject.nameId`. I changed it to `name` and got a match on the email in AD. 
(actually I changed it to `email` first, and got an error in the logs saying the attribute could not be matched and providing a list of possible attributes and values where I found `name` was what I wanted).

**Comment by CasVissers-360ERP** [comment]
@gurneyalex Any success on resolving the issue? We are facing the same issue in combination with Azure AD.

Edit: @gurneyalex nevermind was running an old version, must be Friday.

**Comment by CasVissers-360ERP** [comment]
@BloodMotion I think this ticket can be closed?

**Comment by benjauger** [comment]
@CasVissers-360ERP hello, unfortunatly no.

I tryed once again today and I got the same result (Odoo fresh install), I get stuck at the same step (cf logs below).
The authentication is doing well through ADFS:

```code
saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
```

But right after that, for an unknown reason, an error is thrown and the authentication fail.

Here is my config (GUI) from Odoo SAML backend:

![image](https://user-images.githubusercontent.com/7927528/178148841-89e308ca-155e-45ea-b712-67e1d7cad70c.png)

And here is the log:

```code
2022-07-10 13:57:10,478 99 INFO odoo_backup saml2.client: destination to provider: https://sso.foo.com/adfs/ls/ 
2022-07-10 13:57:10,478 99 INFO odoo_backup saml2.entity: REQUEST: <ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-oIu6BOoctWzOR6w6d" Version="2.0" IssueInstant="2022-07-10T13:57:10Z" Destination="https://sso.foo.com/adfs/ls/" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://v2.odoo.foo.com/auth_saml/signin"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://v2.odoo.foo.com/odoo-saml/prodfoov2</ns1:Issuer></ns0:AuthnRequest> 
2022-07-10 13:57:10,478 99 INFO odoo_backup saml2.client: AuthNReq: <ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" ID="id-oIu6BOoctWzOR6w6d" Version="2.0" IssueInstant="2022-07-10T13:57:10Z" Destination="https://sso.foo.com/adfs/ls/" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://v2.odoo.foo.com/auth_saml/signin"><ns1:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://v2.odoo.foo.com/odoo-saml/prodfoov2</ns1:Issuer></ns0:AuthnRequest> 
2022-07-10 13:57:10,478 99 INFO odoo_backup saml2.entity: HTTP REDIRECT 
2022-07-10 13:57:10,484 99 INFO odoo_backup werkzeug: 172.16.3.202 - - [10/Jul/2022 13:57:10] "GET /auth_saml/get_auth_request?pid=1 HTTP/1.1" 303 - 8 0.002 0.098
2022-07-10 13:57:10,696 99 INFO odoo_backup saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status> 
2022-07-10 13:57:10,714 99 INFO odoo_backup saml2.response: Subject NameID: <ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">benjamin@foo.com</ns0:NameID> 
2022-07-10 13:57:10,715 99 INFO odoo_backup saml2.client_base: --- ADDED person info ---- 
2022-07-10 13:57:10,718 99 INFO odoo_backup odoo.addons.auth_saml.controllers.main: SAML2: access denied 
2022-07-10 13:57:10,720 99 INFO odoo_backup werkzeug: 172.16.3.202 - - [10/Jul/2022 13:57:10] "POST /auth_saml/signin HTTP/1.1" 303 - 12 0.003 0.120
2022-07-10 13:57:10,765 99 INFO odoo_backup werkzeug: 172.16.3.202 - - [10/Jul/2022 13:57:10] "GET /web/login?saml_error=expired HTTP/1.1" 200 - 18 0.006 0.017
```

**Comment by benjauger** [comment]
I'm just seeing there  the error is a bit different:

Before it was:
```code
odoo.addons.base.models.res_users: Login failed for db:odoo login:benjamin@foo.com from 172.16.3.202
```

Now it's:
```code
doo.addons.auth_saml.controllers.main: SAML2: access denied
```
@vincent-hatakeyama this error (SAML2: access denied) is raised in wich context (maybe a dumb question ^^) ?

**Comment by BloodMotion** [comment]
Visiblement mon erreur vient d'ici, je vais continuer d'investiguer : 
https://github.com/OCA/server-auth/blob/667f2e597fe883d4335da589cf8148aa525100be/auth_saml/controllers/main.py#L125

**Comment by benjauger** [comment]
Nevermind, the `SAML2: access denied` error was due to the fact that I didn't created a user with SAML association.
Now I'm facing a new issue, the login happen but the call back to `/auth_saml/signin` provoke an Odoo crash:

```code
2022-07-10 16:23:46,958 99 WARNING ? odoo.service.server: Thread <Thread(odoo.service.http.request.139728806528768, started 139728806528768)> virtual real time limit (165/120s) reached. 
2022-07-10 16:23:46,959 99 INFO ? odoo.service.server: Dumping stacktrace of limit exceeding threads before reloading 
2022-07-10 16:23:46,963 99 INFO ? odoo.tools.misc: 
# Thread: <Thread(odoo.service.http.request.139728806528768, started 139728806528768)> (db:odoo_backup) (uid:n/a) (url:http://v2.odoo.foo.com/auth_saml/signin)
File: "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
  self._bootstrap_inner()
File: "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[...]
2022-07-10 16:23:46,963 99 INFO ? odoo.service.server: Initiating server reload
```

**Comment by benjauger** [comment]
@CasVissers-360ERP @vincent-hatakeyama fixed !
My lastest error was due to a bad mapping of AD attributes (I just tried again by deleting them).

I can confirm that the module is working with Odoo v15,

Thanks for the help, I can now close this ticket (I guess the upgrade of the module solve the problem).

**Comment by dazenkilla** [comment]
Hi @BloodMotion, will you share what you do besides migrated to 15.0 ? Because mine still error exactly like yours before.

**Comment by fg419** [comment]
hello 
i use odoo auth_saml, at the end of authentification, i've error log: "saml2 : failure -matching attribute mail not found in user attrs: {}
i have put "mail" in the field "identity provider matching attribute"
what is wrong ?
please help

**Comment by albieta** [comment]
> hat I didn't created a user with SAML association.

Hi, I am facing the same error: 
```
2023-09-17 16:51:47,497 1 INFO test saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
2023-09-17 16:51:47,575 1 INFO test saml2.response: Subject NameID: <ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" SPNameQualifier="http://unite.pre.upc.edu/auth_saml/metadata?p=5&amp;d=test" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_574bc7c9b1732f66b01ce2f28a8dd116cf9667f22a</ns0:NameID>
2023-09-17 16:51:47,578 1 INFO test saml2.client_base: --- ADDED person info ----
2023-09-17 16:51:47,585 1 INFO test odoo.addons.auth_saml.controllers.main: SAML2: access denied

```
Could you specify more of how you fixed? What do you mean you hadn't created a user with SAML association?
Thank you

**Comment by albieta** [comment]
> > hat I didn't created a user with SAML association.
> 
> Hi @BloodMotion , I am facing the same error:
> 
> ```
> 2023-09-17 16:51:47,497 1 INFO test saml2.response: status: <ns0:Status xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol"><ns0:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" /></ns0:Status>
> 2023-09-17 16:51:47,575 1 INFO test saml2.response: Subject NameID: <ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" SPNameQualifier="http://unite.pre.upc.edu/auth_saml/metadata?p=5&amp;d=test" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_574bc7c9b1732f66b01ce2f28a8dd116cf9667f22a</ns0:NameID>
> 2023-09-17 16:51:47,578 1 INFO test saml2.client_base: --- ADDED person info ----
> 2023-09-17 16:51:47,585 1 INFO test odoo.addons.auth_saml.controllers.main: SAML2: access denied
> ```
> 
> Could you specify more of how you fixed? What do you mean you hadn't created a user with SAML association? Thank you
