### ISSUE TITLE
Verify Email at Signup, error at installation (email-validator is installed)

### ISSUE THREAD

**Issue by l-arnold** [OCA/server-auth#616]
After running 
pip3 install email-validator 
always returns an error at install.

## Describe the bug
All other modules are installing.  This one however, after running 
pip3 install email-validator always returns an error at install.

`All other modules are installing.  This one however, after running 
pip3 install email-validator always returns an error at install.`

## To Reproduce
Server-Auth installed

Update Modules List

**Expected behavior**
Expect it to install, or the error to state clearly the issue:

**Additional context**
Debian.  Use PIP3.  Have been running system for 3 years.

Full Odoo Error is the following:
`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 460, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 178, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 385, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/addons_oca/server-auth/auth_signup_verify_email/__init__.py", line 4, in <module>
    from . import controllers
  File "/opt/odoo/addons_oca/server-auth/auth_signup_verify_email/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/opt/odoo/addons_oca/server-auth/auth_signup_verify_email/controllers/main.py", line 6, in <module>
    from email_validator import EmailSyntaxError, EmailUndeliverableError, validate_email
  File "/usr/local/lib/python3.7/dist-packages/email_validator/__init__.py", line 6, in <module>
    from .validate_email import validate_email
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
  File "/usr/local/lib/python3.7/dist-packages/email_validator/validate_email.py", line 10
    /,  # prior arguments are positional-only
    ^
SyntaxError: invalid syntax`

**Comment by l-arnold** [comment]
I believe this is related to the email-validator package (pip3) as I had the same error also trying to install Email Format Checker which also requires the email-validator package.

Perhaps Odoo on my server has a specific set of python PIP3 packages that are different than those installed generically into Debian, particularly from a "top level" folder, ie /

**Comment by l-arnold** [comment]
I am running Python 3.7 on the server and I see in this history on that line that the commit "before" the current one says: 
` # /, # not supported in Python 3.6, 3.7  `
(line 8 at the time)

The line in the current PIP is (line 10 in the current)
`   /,  # prior arguments are positional-only`

It looks like I need to take out the current email-validator and install the earlier one.  Somewhat of a new exploration for me, but I will find how to install that one  (that or perhaps try a simple # before line 10, but I think there would be more issues left.

**Comment by l-arnold** [comment]
Yes, the current version installed by pip3 is specifically for Python 3.8 only.  Says so in the first line on Github.

April 23, 2023 looks that it is the 3.7 python version.  Looking (in my untrained way) it seems these recent versions might be available but I need to tie them out to the dates next.  2.1.0 is not working.
Earlier ones in the 1.x range also.

2.0.0.dev1, 2.0.0.dev2, 2.0.0.dev3, 2.0.0.dev4, 2.0.0, 2.0.0.post1, 2.0.0.post2, 2.1.0)

**Comment by l-arnold** [comment]
ran first:  pip3 unistall email-validator
then ran
pip3 install email-validator==2.0.0

Got past the error at install to "Verify Email at Signup".
I will test tommorrow.  I will close once I get a simple test run.
